version: "3"

services:
  app:
    image: node:8.9.1
    ports:
      - 3000:3000
    working_dir: /usr/share/app
    command: ["npm", "start"]
    volumes:
      - ./:/usr/share/app
    restart: unless-stopped
